### PR TITLE
Added intro section

### PR DESCRIPTION
**Pull request by nlharris**
hope I did this right

### CODE REVIEW

**Comment by nlharris** [comment]
🤷‍♀️

**Comment by nlharris** [comment]
I don't know whether my changes caused the check to fail or whether it would have failed without my change. Hopefully @hrshdhgd can help when he returns.

**Comment by hrshdhgd** [comment]
Hey @nlharris , thank you for this change. The cause of this error is that it is looking for `intro.rst` file on account of adding it to `index.rst`. I see that the file was added in #86 . If you combine these changes into one PR (same branch) the error will go away.

**Comment by hrshdhgd** [comment]
I have combined both your PRs into one: #88 . Please let me know if something doesn't look right.

**Pull request closed without merging**
